top作成
kana-w/last-issue pull request #3
Opened 2020-07-15 09:19 UTC by kana-w

2020-07-15 10:36 UTC, MoAI522 reviewed
見た目は完璧ですごいと思います。無理やりpaddingでそろえるのだけやめましょう。

2020-07-15 10:36 UTC, MoAI522 commented on index.html
> +        <p>そうだ。<br />カフェに行こう。</p>
画像に合わせて文字の色を黒っぽいやつにしてるの素晴らしいと思います。

2020-07-15 10:36 UTC, MoAI522 commented on index.html
> +        </p>
タブレット表示（スマホ表示に切り替わるギリギリの部分）のとき、文字の左右の余白がなくなってしまうので、つけましょう。
<img width="749" alt="review04" src="https://user-images.githubusercontent.com/64251336/87531705-0f915700-c6cd-11ea-985f-8bdd44a3343b.png">

2020-07-15 10:36 UTC, MoAI522 commented on index.html
> +      <div class="top-img">
top-imgとtop-overviewをひとまとまりとして考えたいので、\<section\>タグでこの二つをくくってみましょう。この時に、\<section\>タグに分かりやすい**id** （classではない）をつけておきましょう。
そして、そのidをstyle.css内のセレクタに含めるようにしましょう。

2020-07-15 10:36 UTC, MoAI522 commented on index.html
> +        </div>
見出しという意味では\<h1\>とか\<h2\>タグを使ったほうがいいかもしれません。

2020-07-15 10:36 UTC, MoAI522 commented on index.html
> +          <br />学校・仕事帰りに、平日の日中に、休日にゆっくり...さまざまなライフスタイルに合わせてご利用いただける多彩なプランをご用意しております。
\<br \\\>でも全く問題ないですし、これからHTMLの規格が変わってこの書き方が標準になっていくかもしれないのですが、現状はスラッシュはなしで\<br\>と書くのが一般的なので、特にこだわりがなければこっちにしておきましょう。

2020-07-15 10:36 UTC, MoAI522 commented on style.css
> +  position: absolute;
top-imgにposition: absolute;を指定すると他の要素がこれの下に潜り込んでしまいます。それを防ぐためにtop-overviewの上paddingを780pxにしてますね。このやり方で要素を並べていくとページの下につく頃にはpaddingの値がとんでもないことになります。やめときましょう。
おそらく「そうだカフェ行こか」の座標の基準をこの要素にするためにposition: absolute;を指定したと思うのですが、同じことがposition: relative;でも可能で、しかも次の要素が下に並んでくれます。

2020-07-15 10:36 UTC, MoAI522 commented on style.css
> +  font-family: 'Times New Roman', Times, serif;
結局タイトルと本文にそれぞれ別のフォントを指定しているので、ここで指定する必要はないでしょう。消しましょう。

2020-07-15 10:36 UTC, MoAI522 commented on style.css
> +  height: 730px;
[8n pxの法則](https://ameblo.jp/ca-1pixel/entry-11837685575.html)という、余白や要素の幅・高さは8の倍数で構成するべきとする考え方があります。特に理由がなければ、表示が崩れない範囲で8の倍数を使いましょう。

2020-07-15 15:04 UTC, momoogles requested changes

2020-07-15 15:04 UTC, momoogles commented on style.css
> +  transform: translate(-50%, -50%);
```css
node {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```
この中央配置の仕方はあんまし直感的でない+今回の場合このp要素は`position: absolute`である必要がなくて行数を減らせるので親要素を`display: flex`にして中央配置してみましょう！！

ただそのやり方も時には使える場合があると思うので悪いというわけではないです！

2020-07-15 15:04 UTC, momoogles commented on style.css
> +  background-image: url(./image/top.jpg);
https://developer.mozilla.org/ja/docs/Web/CSS/background

画面小さい時に画像がなんの画像かわからないので、backgroundプロパティを使ってbackground-sizeやbackground-positionなんかも上手く使ってあげても良さそうですね！試してみてください！(必要なさそうだったら使わなくても良いです！)

2020-07-15 15:14 UTC, momoogles approved these changes

2020-07-15 15:14 UTC, momoogles commented on style.css
> +  position: absolute;
「そうだ。カフェに行こう。」のp要素を`position: absolute`にしないで実装すれば`position: relative`もいらなくなりますね

2020-07-15 15:14 UTC, momoogles commented on style.css
> +    top: 60%;
多分、「そうだ。カフェに行こう。」のp要素が上によっちゃってるからこうしたんですよね？

そもそも、画面を小さくした時にヘッダーが`position: absolute`で、背景画像と重なるからこうなっちゃうと思うので

```css
@media screen and (max-width: 800px) {
  ...他のCSS

  header {
    position: static;
  }
}
```

と追加しちゃうのはどうでしょう？

他の人はあまりやってない実装ですが、割といい実装だと思います！試してみてください！

2020-07-15 15:14 UTC, momoogles commented on style.css
> +  height: 730px;
「そうだ。カフェに行こう。」のp要素をposition: absoluteにしないで実装すればposition: relativeもいらなくなりますね

2020-07-15 15:15 UTC, momoogles commented on style.css
> +  position: absolute;
「そうだ。カフェに行こう。」のp要素をposition: absoluteにしないで実装すればposition: relativeもいらなくなりますね

2020-07-17 16:51 UTC, kana-w commented on index.html
> +        </div>
始めにh2で設定していたのですが文字の大きさと下のｐとの大きさのバランスが何となく気に入らなくて変更しました。h2の方が一目見たときに見出しだとわかりやすいと思うのですが、基本そのようにしたほうがいいですか？

2020-07-17 16:53 UTC, kana-w commented on index.html
> +          <br />学校・仕事帰りに、平日の日中に、休日にゆっくり...さまざまなライフスタイルに合わせてご利用いただける多彩なプランをご用意しております。
<br>で書いたつもりだったのですが拡張機能のPrettierで保存したときに自動で書き換わってしまうのでそのままにしておきます！

2020-07-17 17:23 UTC, momoogles commented on index.html
> +          <br />学校・仕事帰りに、平日の日中に、休日にゆっくり...さまざまなライフスタイルに合わせてご利用いただける多彩なプランをご用意しております。
https://github.com/prettier/prettier/issues/5246
prettierでスラッシュがつくのはこういう理由みたいです

2020-07-17 17:35 UTC, momoogles commented on index.html
> +          <br />学校・仕事帰りに、平日の日中に、休日にゆっくり...さまざまなライフスタイルに合わせてご利用いただける多彩なプランをご用意しております。
https://github.com/prettier/prettier/issues/5246
Prettierで閉じタグ付くのはこういう理由みたいです

2020-07-18 00:23 UTC, MoAI522 commented on index.html
> +        </div>
基本的にその部分が見出しの意味を持つなら、h1とかh2とかを使うべきです。見た目はCSSでいくらでも変えられるので、HTMLを書く際にはタグを使ってその部分がどんな意味を持つのかを説明することに徹するべきだからです。（こういった”プログラムそのものの意味”を**Semantics** といいます。(参考)[https://developer.mozilla.org/ja/docs/Glossary/Semantics]
h2でバランスが崩れるようでしたらstyle.cssでスタイルを整えてみましょう。

2020-07-18 00:24 UTC, MoAI522 commented on index.html
> +          <br />学校・仕事帰りに、平日の日中に、休日にゆっくり...さまざまなライフスタイルに合わせてご利用いただける多彩なプランをご用意しております。
すみません！自分の勉強不足でした。Prettierの仕様ならそのままで大丈夫です。

2020-07-18 15:13 UTC, MoAI522 reviewed
もうまもなくマージできそうですね。頑張ってください。

2020-07-18 15:13 UTC, MoAI522 commented on style.css
> +    position: static;
top-imgはheaderとは違って、デスクトップ表示時に`position:fixed;`とか指定していないので、`position:static;`で初期値に戻す必要はありません。消しときましょう。

2020-07-18 15:13 UTC, MoAI522 commented on style.css
> +    padding: 0 10px 10px;
「カフェで読書＆コワ～」の下の余白なんですが、kanaさんはまずデスクトップ表示時はmargin-bottomで20px、その後このモバイル表示のpaddingで10pxを指定し、「文字の下の余白」を指定するために二つのプロパティを混同して使っているように思います。今回は表示上まったく問題ありませんが、同じ意味で複数のプロパティをその場その場で使い分けていると混乱のもととなりますので、ここは例えば、
```
padding: 0 10px;
margin-bottom: 30px;
```
として、「文字の下の余白」はmargin-bottomで統一するといいでしょう。

2020-07-19 15:09 UTC, MoAI522 commented
LGTMです。先輩方のレビューを待ちましょう。

2020-07-19 16:32 UTC, momoogles commented
LGTMです〜！混ぜときます！

2020-07-20 11:46 UTC, merged